# Generated by Django 4.1.4 on 2023-10-14 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pythonProject', '0008_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='complete',
            new_name='Complete',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='created',
            new_name='Created',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='title',
            new_name='Title',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='user',
            new_name='User',
        ),
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
    ]
