# Generated by Django 4.1.4 on 2023-10-14 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pythonProject', '0011_task_complete_task_created_task_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='Complete',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
