# Generated by Django 4.1.4 on 2023-10-14 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pythonProject', '0013_rename_user_task_user'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='task',
            order_with_respect_to='user',
        ),
    ]
