# Generated by Django 4.1.4 on 2023-10-14 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pythonProject', '0014_alter_task_order_with_respect_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rating', models.CharField(max_length=200)),
                ('Msg', models.BooleanField(blank=True, null=True)),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pythonProject.heritagedetails')),
            ],
        ),
    ]
