# Generated by Django 4.1.4 on 2023-10-14 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pythonProject', '0016_rename_user_review_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='Msg',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='task',
            name='Title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
